### ISSUE TITLE
add-bundle-to-fbc does not add channel

### ISSUE THREAD

**Issue by plagerweij** [redhat-openshift-ecosystem/operator-pipelines#791]
When trying to add a new channel to a basic template using `add-bundle-to-fbc`, it does not pick up the new channel:

```yaml
# ci.yaml
---
updateGraph: replaces-mode

fbc:
  enabled: true
  catalog_mapping:
  - template_name: basic.yaml
    catalog_names: ["v4.17"]
    type: olm.template.basic
```

```yaml
# release-config.yaml
---
catalog_templates:
  - template_name: basic.yaml
    channels: [stable]
```

```yaml
# basic.yaml
---
schema: olm.template.basic
entries:
- schema: olm.package
  name: memcached-operator
  defaultChannel: alpha
- schema: olm.channel
  name: alpha
  package: memcached-operator
  entries:
  - name: memcached-operator.v0.0.1
- schema: olm.bundle
  image: memcached-operator-bundle:v0.0.1
```

Then after running `add-bundle-to-fbc --operator-name memcached-operator --operator-version 0.0.2 --bundle-pullspec ... ` where 0.0.2 has a new stable channel, this is the result:

```yaml
# basic.yaml
---
schema: olm.template.basic
entries:
- schema: olm.package
  name: memcached-operator
  defaultChannel: alpha
- schema: olm.channel
  name: alpha
  package: memcached-operator
  entries:
  - name: memcached-operator.v0.0.1
- schema: olm.bundle
  image: memcached-operator-bundle:v0.0.1
- schema: olm.bundle
  image: memcached-operator-bundle:v0.0.2
```

No errors are present in the logs.

I'm running version `v1.0.165`
